import type { CustomAction } from "./storage";

const SHARED_INSTRUCTION =
  "IMPORTANT: Return ONLY the final rewritten text. Do NOT include any introductory notes, explanations, conversational filler, conversational prefixes, quotes, or markdown wrappers unless markdown was in the original text. Just output the clean rewritten text directly.";

export const BUILTIN_ACTION_DEFAULTS: CustomAction[] = [
  {
    id: "improve",
    name: "Improve writing",
    description: "Polish grammar, flow, and vocabulary",
    icon: "Feather",
    color: "#8B5CF6",
    category: "primary",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Improve the writing quality, grammar, flow, and vocabulary of the following text to make it polished and engaging:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "paraphrase",
    name: "Paraphrase text",
    description: "Rewrite to sound natural and fresh",
    icon: "RefreshCw",
    color: "#3B82F6",
    category: "primary",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Paraphrase the following text to make it sound natural, fresh, and clear while fully maintaining its original meaning:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "fix_spelling",
    name: "Fix spellings and grammer with AI",
    description: "Fix spelling and grammar using AI",
    icon: "Sparkles",
    color: "#F59E0B",
    category: "primary",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Fix all spelling mistakes, typographical errors, and grammatical slips in the following text. Keep it exact and do not change the tone or structure unless necessary to fix errors:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "tone_professional",
    name: "Professional",
    description: "Clear and business-appropriate tone",
    icon: "Briefcase",
    color: "#06B6D4",
    category: "tone",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Rewrite the following text in a clear, professional, and business-appropriate tone:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "tone_casual",
    name: "Casual",
    description: "Friendly and conversational tone",
    icon: "MessageSquare",
    color: "#84CC16",
    category: "tone",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Rewrite the following text in a friendly, conversational, and casual tone:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "tone_exciting",
    name: "Exciting",
    description: "Enthusiastic and engaging tone",
    icon: "Zap",
    color: "#EC4899",
    category: "tone",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Rewrite the following text in an enthusiastic, engaging, and exciting tone:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "tone_friendly",
    name: "Friendly",
    description: "Warm and polite tone",
    icon: "Heart",
    color: "#EF4444",
    category: "tone",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Rewrite the following text in a warm, polite, and friendly tone:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "length_shorter",
    name: "Shorter",
    description: "Concise and direct",
    icon: "Minimize2",
    color: "#8B5CF6",
    category: "length",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Shorten the following text to make it extremely concise and direct while preserving the main message:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
  {
    id: "length_longer",
    name: "Longer",
    description: "Expand with relevant details",
    icon: "Maximize2",
    color: "#3B82F6",
    category: "length",
    type: "builtin",
    replaceMode: "replace",
    enabled: true,
    createdAt: 0,
    promptTemplate: `Expand the following text by adding relevant details and descriptive depth to make it more comprehensive, without changing the core meaning:\n\n"{{input}}"\n\n${SHARED_INSTRUCTION}`,
  },
];
